# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1fd2ce5cba398bf39981f76fffac12d9e5cb72a771d3d9b9d6ddb5e924fb3480d8b8fa67b445135ef7dba8f4927223c2e9ab45ed98c5442459f95fbaf0ee72e

test:
  secret_key_base: 2631cf6a6b0e09698c714014b96ad274cc9bc4c024e2988713a0620257fbbcf7807223a85d9c3abd6b75c189e28ae236c9e639ff4521e442739b54bec6fa4dc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
